import cazaTalentosHero from '../../assets/image/projects/caza-talentos-hero.jpg'
import uesgModaLogo from '../../assets/image/projects/uesg-moda-logo.png'
import vendedoresUesgImage from '../../assets/image/projects/vendedores uesg.png'

export const projects = [
  {
    id: '03',
    fileName: 'vendedores_uesg.exe',
    title: 'Vendedores UESG',
    category: 'FULL STACK / PWA',
    description: 'Sistema multirol para gestionar vendedores, pedidos, inventario, incentivos y reportes de ventas.',
    contribution: 'Desarrollo full stack y experiencia móvil PWA.',
    features: ['Autenticación multirol', 'Pedidos con código de barras', 'Stock y reportes XLSX'],
    technologies: [
      { name: 'React', level: 'Principal', icon: 'react' },
      { name: 'Supabase', level: 'Uso alto', icon: 'supabase' },
      { name: 'PostgreSQL', level: 'Uso alto', icon: 'postgresql' },
      { name: 'Vite', level: 'Complementario', icon: 'vite' },
    ],
    preview: 'sales',
    image: vendedoresUesgImage,
    imageVariant: 'vendedores',
    repositoryUrl: 'https://github.com/rj7rivera/Vendedores-UESG-',
    demoUrl: null,
  },
  {
    id: '04',
    fileName: 'caza_talentos.exe',
    title: 'Caza de Talentos',
    category: 'FULL STACK / E-COMMERCE',
    description: 'Plataforma responsive de productos personalizados y servicios creativos con catálogo, favoritos, carrito, cotizaciones y administración local.',
    contribution: 'Desarrollo full stack, arquitectura de componentes y experiencia de personalización.',
    features: ['Personalizador con texto e imágenes', 'Carrito y favoritos persistentes', 'Pedidos, catálogo y panel administrativo'],
    technologies: [
      { name: 'React', level: 'Principal', icon: 'react' },
      { name: 'Express', level: 'Uso alto', icon: 'express' },
      { name: 'Tailwind CSS', level: 'Uso medio', icon: 'tailwind' },
      { name: 'Vite', level: 'Complementario', icon: 'vite' },
    ],
    preview: 'image',
    image: cazaTalentosHero,
    imageVariant: 'caza-talentos',
    repositoryUrl: 'https://github.com/rj7rivera/CazaTalento',
    demoUrl: 'https://caza-talento.vercel.app/',
  },
  {
    id: '05',
    fileName: 'matriculacion_rj7.exe',
    title: 'Sistema de Matriculación',
    category: 'FULL STACK / EDUCACIÓN',
    description: 'Plataforma académica para gestionar estudiantes, representantes, cupos, rubros y reportes institucionales.',
    contribution: 'Desarrollo full stack y modelado del flujo de matriculación.',
    features: ['Gestión de alumnos y representantes', 'Cupos y rubros académicos', 'Reportes PDF'],
    technologies: [
      { name: 'React', level: 'Principal', icon: 'react' },
      { name: 'Supabase', level: 'Uso alto', icon: 'supabase' },
      { name: 'PostgreSQL', level: 'Uso medio', icon: 'postgresql' },
      { name: 'jsPDF', level: 'Complementario', icon: 'javascript' },
    ],
    preview: 'enrollment',
    repositoryUrl: 'https://github.com/rj7rivera/Sistema-Matriculacion-RJ7',
    demoUrl: 'https://sistema-matriculacion-rj7.vercel.app/',
  },
  {
    id: '06',
    fileName: 'uesg_moda.exe',
    title: 'UESG Moda',
    category: 'FRONTEND / CATÁLOGO',
    description: 'Catálogo responsive multipágina para presentar colecciones de moda, personalización DTF y contenido editorial.',
    contribution: 'Desarrollo frontend del catálogo y sus recorridos de navegación.',
    features: ['Colecciones Urban, Sports y Recover', 'Sección de personalización DTF', 'Carruseles y blog'],
    technologies: [
      { name: 'HTML5', level: 'Principal', icon: 'html' },
      { name: 'CSS3', level: 'Uso alto', icon: 'css' },
      { name: 'JavaScript', level: 'Uso medio', icon: 'javascript' },
      { name: 'Owl Carousel', level: 'Complementario', icon: 'javascript' },
    ],
    preview: 'sales',
    image: uesgModaLogo,
    repositoryUrl: 'https://github.com/rj7rivera/UESG---MODA',
    demoUrl: null,
  },
]